<a href="https://colab.research.google.com/github/saikiran76/Finetune-model-space/blob/master/FrankensteinQLoRAStarter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install -q -U bitsandbytes
!pip install -q -U transformers
!pip install -q -U peft
!pip install -q -U accelerate
!pip install -q -U datasets
# !pip install -q -U pandas # you don't need to install either of these last two libs if you're using Colab
# !pip install -q -U torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 15.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 108.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 19.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 16.2 MB/s eta 0:00:00

In [3]:
import random
import torch
import pandas as pd
from datasets import Dataset
import peft
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
def set_seed(seed=42):
    random.seed(seed)
    torch.manual_seed(seed)

set_seed()

In [4]:
mistral7b = 'mistralai/Mistral-7B-v0.1'
# STEP 1. Check and make sure you're using the right model and notebook here.
model_name = mistral7b

## EDA

In [5]:
df = pd.read_csv("/content/drive/MyDrive/Transformers-AI/frankenstein_chunks.csv")
df.head()

                                                text
0  ﻿The Project Gutenberg eBook of Frankenstein; ...
1  Further corrections by Menno de Leeuw.\n\n\n**...
2  I am already far north of London, and as I wal...
3  Its productions and features may be without ex...
4  But supposing all these conjectures to be fals...

In [6]:
print("Dataframe Info:")
print(df.info())
print("\n")
print("Dataframe Description:")
print(df.describe())
print("\n")
print("Number of unique values in each column:")
print(df.nunique())
random_index= random.randint(0, len(df) - 1)
df.loc[random_index, 'text']

Dataframe Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    481 non-null    object
dtypes: object(1)
memory usage: 3.9+ KB
None


Dataframe Description:
                                                     text
count                                                 481
unique                                                481
top     International donations are gratefully accepte...
freq                                                    1


Number of unique values in each column:
text    481
dtype: int64

'The thatch had fallen in, the walls were unplastered, and the\ndoor was off its hinges. I ordered it to be repaired, bought some\nfurniture, and took possession, an incident which would doubtless have\noccasioned some surprise had not all the senses of the cottagers been\nbenumbed by want and squalid poverty. As it was, I lived ungazed at\nand unmolested, hardly thanked for the pittance of food and clothes\nwhich I gave, so much does suffering blunt even the coarsest sensations\nof men.\n\nIn this retreat I devoted the morning to labour; but in the evening,\nwhen the weather permitted, I walked on the stony beach of the sea to\nlisten to the waves as they roared and dashed at my feet. It was a\nmonotonous yet ever-changing scene. I thought of Switzerland; it was\nfar different from this desolate and appalling landscape. '

In [7]:
df.isnull().sum()

text    0
dtype: int64

In [8]:
# Now we'll quickly convert this to a train/test split
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df, test_size=0.2)

# STEP 2. Convert the train_df and test_df from Pandas into Hugging Face Datasets
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

## Model Import and Tokenization

In [9]:
quant_config = BitsAndBytesConfig(
  # STEP 3. Pass the appropriate parameters here to 4-bit quantize the model, then instantiate the model and check what it's running on.
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_compute_dtype=torch.bfloat16
)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quant_config,
    device_map="auto"
)
print("\n\nModel is running on:" + "\n")
model

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Model is running on:

MistralForCausalLM(
  (model): MistralModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x MistralDecoderLayer(
        (self_attn): MistralAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
        )
        (mlp): MistralMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): MistralRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): MistralRMSNorm((4096,), eps=1e-05)
      )
    )
    (norm): MistralRMSNorm((4096,), eps=1e-05)
    (rotary_emb): MistralRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)

In [10]:
from peft import prepare_model_for_kbit_training, LoraConfig, get_peft_model, TaskType

# STEP 4. Prepare the model for QLoRA. Configure LoRA for our finetuning run. Then tokenize the data.
model = prepare_model_for_kbit_training(model)
config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.01,
    task_type=TaskType.CAUSAL_LM
)

model = get_peft_model(model, config)
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_data(data):
  return tokenizer(data['text'], padding='longest', truncation=True)

tokenized_train_dataset= train_dataset.map(tokenize_data, batched=True)
tokenized_test_dataset = test_dataset.map(tokenize_data, batched=True)

tokenizer_config.json:   0%|          | 0.00/996 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

Map:   0%|          | 0/384 [00:00<?, ? examples/s]

Map:   0%|          | 0/97 [00:00<?, ? examples/s]

## Base Model Evaluation

In [11]:
def generate_text(prompt):
  device = "cuda"
  inputs = tokenizer(prompt, return_tensors="pt").to(device)
  outputs = model.generate(**inputs, max_new_tokens=100)
  output = tokenizer.decode(outputs[0], skip_special_tokens=True)
  return output

In [12]:
# STEP 5. Generate a completion with the base model for informal evaluation.
base_generation = generate_text(train_dataset['text'][0])
base_generation

[transformers] Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

'You, perhaps, regard her as your sister, without any\nwish that she might become your wife. Nay, you may have met with another\nwhom you may love; and considering yourself as bound in honour to\nElizabeth, this struggle may occasion the poignant misery which you appear\nto feel.”\n\n“My dear father, reassure yourself. I love my cousin tenderly and\nsincerely. I never saw any woman who excited, as Elizabeth does, my\nwarmest admiration and affection. My future hopes and prospects are\nentirely bound up in the expectation of our union.”\n\n“The expression of your sentiments of this subject, my dear Victor,\ngives me more pleasure than I have for some time experienced. If you\nfeel thus, we shall assuredly be happy, however present events may cast\na gloom over us. But it is this gloom which appears to have taken so\nstrong a hold of your mind that I wish to dissipate. 1 am not\nunaware of the difficulties which have arisen in your affairs, but I\nhope that they will be speedily removed. I have no doubt that your\nfriends will be able to assist you in this, and that you will be able to\nrecover your fortune.”\n\n“I am not so sanguine, my dear father. I have been unfortunate in\neverything. I have lost my fortune, my friends, and my happiness. I\n'

In [15]:
def calc_perplexity(model):
  total_perplexity = 0
  device = "cuda"
  for row in test_dataset:
    inputs = tokenizer(row['text'], return_tensors="pt").to(device)
    input_ids = inputs["input_ids"]
    # Calculate the loss without updating the model
    with torch.no_grad():
        outputs = model(**inputs, labels=input_ids)
    loss = outputs.loss
    # STEP 6. Complete the equation for perplexity.
    perplexity = torch.exp(loss)
    total_perplexity += perplexity

  num_test_rows = len(test_dataset)
  avg_perplexity = total_perplexity / num_test_rows
  return avg_perplexity

base_ppl = calc_perplexity(model)
base_ppl

tensor(9.0925, device='cuda:0')

## Training

Make sure you can leave your browser open for a while. This took about 15 minutes on a Colab T4 GPU.

In [17]:
import transformers

tokenizer.pad_token = tokenizer.eos_token
model.config.use_cache = False

trainer = transformers.Trainer(
    model=model,
    train_dataset=tokenized_train_dataset,
    args=transformers.TrainingArguments(
        warmup_steps=2,
        fp16=True,
        logging_steps=1,
        save_steps=200,
        output_dir="outputs",
      # STEP 7. Configure the training arguments.
        per_device_train_batch_size=2,
        num_train_epochs=2,
        learning_rate=2e-5,
        optim="paged_adamw_8bit"
    ),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
)
# STEP 8. Finetune the model.
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

TrainOutput(global_step=384, training_loss=1.8418687558732927, metrics={'train_runtime': 1170.1347, 'train_samples_per_second': 0.656, 'train_steps_per_second': 0.328, 'total_flos': 1.079032113266688e+16, 'train_loss': 1.8418687558732927, 'epoch': 2.0})

## Evaluating the finetuned model

In [23]:
import random

# STEP 9. Generate a completion with the finetuned model and compare it to the base generation.
# Select a random sample from the test_dataset for generation
random_test_index = random.randint(0, len(test_dataset) - 1)
sample_text_for_generation = test_dataset['text'][random_test_index]

ft_generation = generate_text(sample_text_for_generation)

print("Base model generation (from train_dataset[0]):\n" + base_generation + "\n\n")
print(f"Finetuned generation (from test_dataset[{random_test_index}]):\n{ft_generation}")

[transformers] Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
[transformers] `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
[transformers] Caching is incompatible with gradient checkpointing in MistralDecoderLayer. Setting `past_key_values=None`.
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/utils/checkpoint.py:232: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  check_backward_validity(args)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Base model generation (from train_dataset[0]):
You, perhaps, regard her as your sister, without any
wish that she might become your wife. Nay, you may have met with another
whom you may love; and considering yourself as bound in honour to
Elizabeth, this struggle may occasion the poignant misery which you appear
to feel.”

“My dear father, reassure yourself. I love my cousin tenderly and
sincerely. I never saw any woman who excited, as Elizabeth does, my
warmest admiration and affection. My future hopes and prospects are
entirely bound up in the expectation of our union.”

“The expression of your sentiments of this subject, my dear Victor,
gives me more pleasure than I have for some time experienced. If you
feel thus, we shall assuredly be happy, however present events may cast
a gloom over us. But it is this gloom which appears to have taken so
strong a hold of your mind that I wish to dissipate. 1 am not
unaware of the difficulties which have arisen in your affairs, but I
hope that they will be speedily removed. I have no doubt that your
friends will be able to assist you in this, and that you will be able to
recover your fortune.”

“I am not so sanguine, my dear father. I have been unfortunate in
everything. I have lost my fortune, my friends, and my happiness. I



Finetuned generation (from test_dataset[81]):
I remained,
while the storm lasted, watching its progress with curiosity and delight.
As I stood at the door, on a sudden I beheld a stream of fire issue from an
old and beautiful oak which stood about twenty yards from our house; and so
soon as the dazzling light vanished, the oak had disappeared, and nothing
remained but a blasted stump. When we visited it the next morning, we found
the tree shattered in a singular manner. It was not splintered by the
shock, but entirely reduced to thin ribbons of wood. I never beheld
anything so utterly destroyed.

Before this I was not unacquainted with the more obvious laws of
electricity. On this occasion a man of great research in natural
philosophy was with us, and excited by this catastrophe, he entered on
the explanation of a theory which he had formed on the subject of
electricity and galvanism, which was at once new and astonishing to me.
He was a  #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #
 bekanen, #

A little more like the original text, right? Try experimenting with the hyperparameters to see if you can improve performance.

In [24]:
# STEP 10. Calculate the finetuned model's perplexity and compare it to the base model's.
ft_ppl = calc_perplexity(model)
print("Base model perplexity: " + str(base_ppl))
print("Finetuned model perplexity: " + str(ft_ppl))

Base model perplexity: tensor(9.0925, device='cuda:0')
Finetuned model perplexity: tensor(6.8822, device='cuda:0')